Update fr.json
theRealPadster/spicetify-hide-podcasts pull request #134
Opened 2024-03-23 21:43 UTC by Resxt

Changed "balados" (not a real word) to "podcasts"
Added "hideAudiobooks" translation

2024-03-23 22:37 UTC, theRealPadster commented
When I google "balados", it seems to mean podcasts? 
<img width="719" alt="image" src="https://github.com/theRealPadster/spicetify-hide-podcasts/assets/1565883/63bf990e-4560-4cda-bdb8-cda344b899e2">

2024-03-24 00:03 UTC, theRealPadster commented
If it's a Canadian/Quebec French thing, can you add an override to a separate locale file? Like how we have "en" and "en-US"? They have different languages in Spotify. 
![image](https://github.com/theRealPadster/spicetify-hide-podcasts/assets/1565883/0983cba7-ab93-45d4-a79d-241e692aee10)

2024-03-24 08:34 UTC, Resxt commented
I don't speak or understand anything canadian so no, I would mess it up.

My opinion is that they still speak french and understand it. Metropolitan french people don't understand canadian but canadians understand "regular french" because their language is based on it.

The words used for this translation are very simple french and they will understand it. Even more since "podcasts" is widely known and since english is like second nature in a lot of places there

2024-03-24 12:52 UTC, theRealPadster commented
You don't need to include every string, I just meant to move the current "balados" ones to a French Canadian file, and then we update the main fr.json.

2024-03-25 14:54 UTC, theRealPadster requested changes
We just need the changed keys. It will default to the regular "fr.json" version for anything missing.

2024-03-25 14:54 UTC, theRealPadster commented on src/locales/fr-CA.json
> +    "search": {}
```suggestion
      "title": "Masquer les balados"
    }
```

2024-03-28 15:39 UTC, theRealPadster approved these changes

2024-03-28 15:40 UTC, merged