🇨🇳 Add Simplified Chinese locale
theRealPadster/spicetify-hide-podcasts pull request #45
Opened 2022-11-17 11:48 UTC by Wittoy

2022-11-17 21:05 UTC, theRealPadster requested changes
Thanks, just had the one question to make sure it works on the search page. When I test the locale on my computer I get a different translation. Just let me know if it's correct or should change and we should be good to go :)

2022-11-17 21:05 UTC, theRealPadster commented on src/locales/zh-CN.json
> +    "searchPageShelfAriaLabel": "想听什么？"
Just want to double check that this is the correct translation. It should be the "browse all" label on the search page here:

![image](https://user-images.githubusercontent.com/1565883/202559444-b63417c1-d446-4341-b2e8-4bac3044210a.png)

2022-11-18 01:33 UTC, Wittoy commented on src/locales/zh-CN.json
> +    "searchPageShelfAriaLabel": "想听什么？"
Aha, I understood it to be a search bar placeholder.
Preferably "浏览全部"
```suggestion
    "searchPageShelfAriaLabel": "浏览全部"
```

2022-11-18 02:11 UTC, merged

2022-11-18 02:11 UTC, theRealPadster commented
Awesome thanks!